import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  topIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255, 255, 255, 0.85)",
    letterSpacing: 1,
  },
  headerContent: {
    paddingHorizontal: 20,
    paddingBottom: 25,
    paddingTop: 10,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  mainTitle: {
    fontSize: 27,
    fontWeight: "600",
    color: "#fff",
    letterSpacing: -0.5,
    lineHeight: 32,
  },
  stepCounter: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.8)",
    marginBottom: 4,
  },
  progressBarContainer: {
    flexDirection: "row",
    gap: 6,
    marginTop: 18,
  },
  progressBarSegment: {
    height: 4,
    flex: 1,
    borderRadius: 2,
  },
  progressActive: { backgroundColor: "#fff" },
  progressInactive: { backgroundColor: "rgba(255, 255, 255, 0.3)" },

  bottomCardContainer: {
    flex: 1,
    backgroundColor: "#fffaf8",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
  },
  scrollBody: {
    padding: 20,
    paddingBottom: 40,
  },
  backStepButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
  },
  backStepText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#43504b",
  },
  stepHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  stepNumberCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ffe4df",
    justifyContent: "center",
    alignItems: "center",
  },
  stepNumberText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#c72f27",
  },
  stepTerazLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#be3d35",
    letterSpacing: 1.1,
  },
  stepTitle: {
    fontSize: 19,
    fontWeight: "600",
    color: "#18221f",
    marginTop: 2,
  },
  instructionCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#eee7e2",
    padding: 18,
    boxShadow: "0px 8px 30px rgba(46, 34, 27, 0.05)",
    elevation: 2,
    marginBottom: 16,
  },
  speechCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#eee7e2",
    paddingHorizontal: 20,
    paddingVertical: 28,
    marginBottom: 18,
  },
  speechText: {
    fontSize: 26,
    lineHeight: 34,
    fontWeight: "700",
    color: "#18221f",
    textAlign: "left",
  },
  instructionText: {
    fontSize: 16,
    lineHeight: 24,
    color: "#43504b",
  },
  locationPrompt: {
    fontSize: 20,
    fontWeight: "700",
    color: "#18221f",
    marginBottom: 16,
  },
  locationOption: {
    backgroundColor: "#fff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e7ddd8",
    paddingHorizontal: 18,
    paddingVertical: 16,
    marginBottom: 12,
  },
  locationOptionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#18221f",
    marginBottom: 4,
  },
  locationOptionDescription: {
    fontSize: 13,
    lineHeight: 18,
    color: "#556761",
  },
  locationNote: {
    marginTop: 16,
    fontSize: 13,
    lineHeight: 18,
    color: "#49635a",
    fontWeight: "600",
  },
  decisionGrid: {
    gap: 12,
    marginBottom: 16,
  },
  decisionButton: {
    minHeight: 68,
    backgroundColor: "#fff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#d9cbc2",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  decisionButtonText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#18221f",
    textAlign: "center",
  },
  repeatSpeechButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 16,
  },
  repeatSpeechText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#49635a",
  },
  primaryButton: {
    height: 54,
    backgroundColor: "#285c49",
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    boxShadow: "0px 10px 24px rgba(40, 92, 73, 0.2)",
    elevation: 4,
    marginBottom: 16,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
  emergencyCallRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    height: 40,
  },
  emergencyCallText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#a33731",
  },
});
