import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fffaf8",
  },
  topHeader: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 4,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: "700",
    color: "#7b8883",
    letterSpacing: 1.2,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 20,
  },
  pageTitle: {
    fontSize: 30,
    fontWeight: "600",
    color: "#18221f",
    letterSpacing: -0.5,
    marginTop: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 13,
    color: "#6b7571",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 4,
  },
  radarContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
  },
  radarRingOuter: {
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: "#edf3f0",
    alignItems: "center",
    justifyContent: "center",
  },
  radarRingInner: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "#dfeae5",
    alignItems: "center",
    justifyContent: "center",
  },
  radarCenterCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#2b5243",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0px 8px 20px rgba(43, 82, 67, 0.25)",
    elevation: 4,
  },
  waveformContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    height: 50,
  },
  bar: {
    width: 4,
    backgroundColor: "#315d4d",
    borderRadius: 2,
  },
  analyzingText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#6b7571",
    marginTop: -8,
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5ece8",
    borderRadius: 20,
    padding: 16,
    width: "100%",
    gap: 12,
    boxShadow: "0px 4px 16px rgba(0, 0, 0, 0.03)",
    elevation: 1,
  },
  infoIconBox: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#edf3f0",
    alignItems: "center",
    justifyContent: "center",
  },
  infoTextContainer: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#18221f",
  },
  infoDescription: {
    fontSize: 12,
    color: "#6b7571",
    marginTop: 2,
  },
  cancelButton: {
    width: "100%",
    height: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#d9e2de",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#283832",
  },
});
